[technote]
id = "DMTN-214"
series_id = "DMTN"
canonical_url = "https://dmtn-214.lsst.io/"
github_url = "https://github.com/lsst-dm/dmtn-214"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
